# This messages just shown as log, not messages to clients

triple_dots = "..."
successful_binding = "Server was launched successfully."
problem_in_binding = "A problem in binding server"
server_closed = "Server was closed."
to_start_server = "To start server type \"start\"."
exiting = "Exiting"
port = "port:"
host = "hostname:"
address = "address:"
waiting = "Waiting"
max_client = "Max clients"
new_connection = "A new connection :"
close_connection = "A connection was closed :"
new_message = "A new message from:"
message_sent = "Message was sent to:"
